module.exports.publicDir = 'src/public'
module.exports.imageExtensions = ['jpg', 'png', 'webp']

module.exports.allowedPathList = [
  '/favicon.ico',
  '/apple-touch-icon.png',
  'https://static-site-template.usagizmo.com',
  'https://fonts.googleapis.com',
  'https://fonts.gstatic.com',
  'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+JP:wght@400;500;700&family=Source+Code+Pro:wght@400;500;600;700&display=swap',
  'https://cdn.jsdelivr.net/npm/yakuhanjp@3.4.1/dist/css/yakuhanjp-noto.min.css',
  'https://github.com/usagizmo/static-site-template',
  'https://tailwindcss.com',
  'https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode',
  'https://htmlhint.com',
  'https://eslint.org',
  'https://prettier.io',
  'https://github.com/okonet/lint-staged',
  'https://github.com/typicode/husky',
  'https://pnpm.io/',
  'https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss',
  'https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint',
  'https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint',
  'https://marketplace.visualstudio.com/items?itemName=webhint.vscode-webhint',
  'https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig',
  'https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode',
  'https://github.com/usagizmo/static-site-template',
  'https://usagizmo.com',
  'https://rollupjs.org/',
  'https://cdn.jsdelivr.net/npm/picturefill@3.0.3/dist/picturefill.min.js',
  'https://cdn.jsdelivr.net/npm/gsap@3.8.0/dist/gsap.min.js',
  'https://cdn.jsdelivr.net/npm/gsap@3.8.0/dist/ScrollToPlugin.min.js',
  'https://cdn.jsdelivr.net/npm/gsap@3.8.0/dist/ScrollTrigger.min.js',
]
