module.exports.publicDir = 'src/public'
module.exports.imageExtensions = ['jpg', 'png', 'webp']

module.exports.allowedPathList = [
  '/apple-touch-icon.png',
  '/favicon.ico',
  'http://localhost:5555',
  'https://cdn.jsdelivr.net/npm/jquery.easing@1.4.1/jquery.easing.min.js',
  'https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js',
  'https://cdn.jsdelivr.net/npm/yakuhanjp@3.4.1/dist/css/yakuhanjp-noto.min.css',
  'https://eslint.org',
  'https://fonts.googleapis.com',
  'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+JP:wght@400;500;700&family=Source+Code+Pro:wght@400;500;600;700&display=swap',
  'https://fonts.gstatic.com',
  'https://github.com/okonet/lint-staged',
  'https://github.com/typicode/husky',
  'https://github.com/usagizmo/static-site-template',
  'https://htmlhint.com',
  'https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss',
  'https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint',
  'https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig',
  'https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode',
  'https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint',
  'https://marketplace.visualstudio.com/items?itemName=webhint.vscode-webhint',
  'https://marketplace.visualstudio.com/items?itemName=yandeu.five-server',
  'https://prettier.io',
  'https://static-site-template.usagizmo.com',
  'https://tailwindcss.com',
  'https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode',
  'https://usagizmo.com',
]
